name: AutoMessage
version: ${project.version}
api-version: 1.20
author: ELCHILEN0
description: Schedule easily configurable broadcasts!
main: com.teamnovus.automessage.AutoMessage
commands:
  automessage:
    description: Main command for all AutoMessage commands
    aliases: [ am ]